# Generated by Django 6.0.3 on 2026-03-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('old_code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True)),
                ('civility', models.CharField(blank=True, max_length=10, null=True)),
                ('born_at', models.DateField(blank=True, null=True)),
                ('born_in', models.CharField(blank=True, max_length=150, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('father_firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('pid', models.CharField(blank=True, max_length=100, null=True)),
                ('type_pid', models.CharField(blank=True, max_length=50, null=True)),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, max_length=150, null=True)),
                ('place', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('connect', models.BooleanField(default=False)),
                ('departure_at', models.DateField(blank=True, null=True)),
                ('user_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agence_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_agent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('working_date_day', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['id'],
            },
        ),
    ]
