# Generated by Django 6.0.3 on 2026-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commerciaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('old_code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cni', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('connect', models.BooleanField(default=False)),
                ('agence_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_agent_id', models.IntegerField(blank=True, null=True)),
                ('code_collect', models.CharField(blank=True, max_length=100, null=True)),
                ('cb_commitment_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('cb_commitment_acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cb_transaction_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('cb_transaction_acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cb_excess_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('cb_excess_acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cb_deficit_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('cb_deficit_acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cb_salary_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('cb_salary_acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'db_table': 'commerciaux',
                'ordering': ['id'],
            },
        ),
    ]
