# Generated by Django 6.0.3 on 2026-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commerciaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('number_of_due_dates', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'En cours'), ('paid', 'Remboursé'), ('cancelled', 'Annulé'), ('overdue', 'En retard')], default='pending', max_length=20)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('backdated', models.BooleanField(default=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('last_due_date', models.DateField(blank=True, null=True)),
                ('working_date_day', models.DateField(blank=True, null=True)),
                ('refund_account', models.CharField(blank=True, max_length=100, null=True)),
                ('periodicity_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_loan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_insurance_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agence_code', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'db_table': 'prets',
                'ordering': ['-created_at'],
            },
        ),
    ]
