# Generated by Django 6.0.3 on 2026-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('can_take_loans', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('standby_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('working_date_day', models.DateField(blank=True, null=True)),
                ('max_date_op', models.DateField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_agent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agence_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_loan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'db_table': 'comptes',
                'ordering': ['-created_at'],
            },
        ),
    ]
