# Generated by Django 6.0.3 on 2026-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('is_use', models.BooleanField(default=True)),
                ('cancel_by', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('working_date_day', models.DateField(blank=True, null=True)),
                ('agence_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_agent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'db_table': 'recus',
                'ordering': ['-created_at'],
            },
        ),
    ]
